#!/bin/env sh

set -e

DB_LOCATION="/usr/share/ffind"
DB_PATH="$DB_LOCATION/ffind.db"

if [ ! "$(id -u)" = 0 ]; then
	printf "Please run ffupdate as root.\n"
	return 1
fi

mkdir -p "$DB_LOCATION"
touch "$DB_PATH"
chmod -R 666 "$DB_LOCATION"
chmod 755 "$DB_LOCATION"

find / 2>/dev/null > $DB_PATH
